apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::954638449514:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-PXVDDQXUZZ8J
      username: system:node:{{EC2PrivateDNSName}}
      rolearn: arn:aws:iam::954638449514:role/UdacityFlaskDeployCBKubectlRole
      username: build
      groups:
        - system:masters
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-05-03T23:21:59Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "948"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 26405dde-6dbb-467c-9f7d-709d7c8ebaea


